### ISSUE TITLE
Request for multithreading support for verilator backend

### ISSUE THREAD

**Issue by Entropy-xcy** [chipsalliance/chisel#1567]
**Type of issue**: feature request | other enhancement

**Impact**: no functional change

**Development Phase**:  proposal

Verilator 4.0 is officially supporting multithreading simulation. As they suggested, this feature gains speedup more than x5 times. Would chisel support this feature in the future?

**Comment by colinschmidt** [comment]
Support for multithreaded verilator was recently added to Chipyard which is a chisel project. You can see that PR here:
https://github.com/ucb-bar/chipyard/pull/654
