### ISSUE TITLE
Improve MuxLookup's type declaration to get better type errors

### ISSUE THREAD

**Issue by jackkoenig** [chipsalliance/chisel#2780]
**Type of issue**: Feature Request

**Is your feature request related to a problem? Please describe.**

When users misuse [MuxLookup](https://javadoc.io/doc/edu.berkeley.cs/chisel3_2.13/3.5.4/chisel3/util/MuxLookup$.html), they can sub-optimal error messages. Consider:
```scala
val sel = IO(Input(Bool()))
val packet0 = IO(Input(Vec(4, UInt(8.W))))
val packet1 = IO(Input(Vec(4, UInt(8.W))))
val out      = IO(Output(Vec(4, UInt(8.W))))

// Call some operation on our Vecs that turn them into Seqs
val choices = Seq(
  0.U -> packet0.map(_ + 1.U),
  1.U -> packet1.map(_ - 1.U)
)

out := MuxLookup(sel, VecInit.fill(4)(0.U), choices)
```
(Scastie: https://scastie.scala-lang.org/ZuJdv3XLQz61C0wmLy57vw)

This gives the error message:
```
Example.scala:16:10: inferred type arguments [chisel3.UInt,IndexedSeq[chisel3.UInt]] do not conform to method apply's type parameter bounds [S <: chisel3.UInt,T <: chisel3.Data]
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices)
         ^
Example.scala:16:20: type mismatch;
 found   : chisel3.Bool
 required: S
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices)
                   ^
Example.scala:16:40: type mismatch;
 found   : chisel3.Vec[chisel3.UInt]
 required: T
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices)
                                       ^
Example.scala:16:47: type mismatch;
 found   : Seq[(chisel3.UInt, IndexedSeq[chisel3.UInt])]
 required: Seq[(S, T)]
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices)
                                              ^
four errors found
```
Now the real issue is that `choices` is a `Seq[(Bool, IndexedSeq[UInt])]` instead of `Seq[(Bool, Vec[UInt])]`, but the error message is pretty bad. It is even misleading in that it suggests the first 2 arguments are wrong.

**Describe the solution you'd like**

We could make some minor changes to MuxLookup to improve the error messages here:

1. Get rid of `S`, it doesn't actually do anything because it isn't part of the return value and since the compiler will choose the least upper bound of `key` and `mapping`, it doesn't actually enforce any benefit.

```scala
object MuxLookup {
  def apply[T <: Data](key: UInt, default: T, mapping: Seq[(UInt, T)]): T
```
(Scastie: https://scastie.scala-lang.org/tEusNBkLTqK7PfBTwCGtuQ)
Then instead you get an error message like this:
```
Example.scala:20:10: inferred type arguments [IndexedSeq[chisel3.UInt]] do not conform to method apply's type parameter bounds [T <: chisel3.Data] 
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices) 
         ^ 
Example.scala:20:40: type mismatch; 
 found   : chisel3.Vec[chisel3.UInt] 
 required: T 
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices) 
                                       ^ 
Example.scala:20:47: type mismatch; 
 found   : Seq[(chisel3.UInt, IndexedSeq[chisel3.UInt])] 
 required: Seq[(chisel3.UInt, T)] 
  out := MuxLookup(sel, VecInit.fill(4)(0.U), choices) 
                                              ^ 
three errors found 
```
Better, but we can do better

2. Use 2 parameter lists so that the type of `mapping` is derived from the type of `default`:

```scala
object MuxLookup {
  def apply[S <: UInt, T <: Data](key: S, default: T)(mapping: Seq[(S, T)]): T
}
```
(Scastie: https://scastie.scala-lang.org/5nJzvhJMTYmiu4CGe74jMQ)
Note that you can even keep `S` here and now it does actually do something. It ensures that if you are using a `Bool` for the `key` that you also use a `Bool` for the keys in the `mapping`. Is this _that_ useful? I'm not sure, but unlike in the current API, it at least does _something_.

Now the error message is:
```
Example.scala:20:47: type mismatch;
 found   : Seq[(chisel3.UInt, IndexedSeq[chisel3.UInt])]
 required: Seq[(chisel3.Bool, chisel3.Vec[chisel3.UInt])]
  out := MuxLookup(sel, VecInit.fill(4)(0.U))(choices)
                                              ^
one error found
```

🤌 perfection

The only big negative here is that it is an API change that would imply deprecating the old version and migrating code. Is it worth it? I think so, but reasonable people can disagree.

**What is the use case for implementing this feature?**

Better error messages.

**Comment by albertchen-sifive** [comment]
We can't have the both versions of the apply method at the same time though because they erase to the same type https://scastie.scala-lang.org/qWpLGPb8Q7qp3lzY0kuxzw. Is protocol here to add a differently named method with the improved signature and deprecate the `apply` method then change the `apply` method in a later version? If so what should the different name be?
