### ISSUE TITLE
Delete LegacyBlackBox

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/chisel#3057]
**Type of issue**: Feature Request

**Is your feature request related to a problem? Please describe.**

We have an `abstract class LegacyBlackBox` which has comments on it that say "don't use this!" and I don't think we use it internally either. We can deprecate in 3.6 and delete in Chisel5

**Describe the solution you'd like**

delete this unused code

**Describe alternatives you've considered**

Keep it around? I think we don't have the legacy behavior anymore...?

**Additional context**

None

**What is the use case for implementing this feature?**

Not having unused APIs to support that say "don't use this!" in the comments.

**Comment by 17Moons** [comment]
i would like to work on this issue

**Comment by jackkoenig** [comment]
Hello again @17Moons and thank you for your interest! It turns out this actually has already been done, so I will close this issue.

Fixed by https://github.com/chipsalliance/chisel/pull/3058.
