### ISSUE TITLE
`hasAlt` in `WhenEnd` should not always be `false`

### ISSUE THREAD

**Issue by SpriteOvO** [chipsalliance/chisel#3435]
**Type of issue**: Feature Request

There is a field `hasAlt` in `WhenEnd` that may be supposed to be set to `true` if the next command is `AltBegin`, but currently it's not set anywhere. I guess it is unimplemented.

**Describe the solution you'd like**
Correctly implement the `hasAlt` field in Chisel.

**Describe alternatives you've considered**
I can also probe the next command myself, but it's a little dirty.

**What is the use case for implementing this feature?**
I'm working on the CIRCT Converter and need to handle all IR commands. For When stuff, I maintained a stack for their contexts, the `hasAlt` is essential to determine if I should pop the context or not when handling `WhenEnd`, if I understand correctly.

**Comment by sequencer** [comment]
Fixed via #4184, Thanks @seldridge
