### ISSUE TITLE
Will Chisel upgrade to Scale3

### ISSUE THREAD

**Issue by xxZhLF** [chipsalliance/chisel#3572]
**Will Chisel upgrade to Scale3**: As described in the title

To learning and using Chilse, I'm reading Scale textbook recently.

Today I realized that the textbook describes Scale3, but Chisel is built on Scale2.

Hence this issue :)

**Comment by Guest-615695028** [comment]
Scala 3

**Comment by jackkoenig** [comment]
Eventually yes, I wrote a little bit about the plan here: https://github.com/chipsalliance/chisel/issues/3768#issuecomment-1912795771. No concrete dates but we would like to move to Scala 3 in the [hopefully not-so-distant] future.
