### ISSUE TITLE
C-API Broken on CIRCT Nightly due to Removal of Unused Argument

### ISSUE THREAD

**Issue by seldridge** [chipsalliance/chisel#3594]
The Chisel C-API needs to be updated to reflect this change: https://github.com/llvm/circt/commit/55505ebcb95a6b5c2c202c3aeae7dd5c3e6bf056

This can be a PR made against the `ci/ci-circt-nightly` branch to get nightly back to green.

**Comment by sequencer** [comment]
Thanks for report!
I'd like to wait for llvm/circt#6315 and (maybe a new version of) #3589, to get CI passed.

**Comment by seldridge** [comment]
The nightly should be green. If it's not then it's delaying a failure that will manifest when CIRCT CD runs. (Chisel won't be able to be bumped to latest CIRCT when the next version is released.)

**Comment by sequencer** [comment]
ok i'll do it today
