### ISSUE TITLE
Nightly CIRCT Failing, Panama Related

### ISSUE THREAD

**Issue by seldridge** [chipsalliance/chisel#3629]
Nightly failed last night due to, assumedly C-API changes: https://github.com/chipsalliance/chisel/actions/runs/6876424861/job/18702016730

CC: @sequencer, @SpriteOvO

**Comment by SpriteOvO** [comment]
PR #3626 included the changes for the new API, but since the PR is still a draft, I will extract those changes to a separate PR ASAP.
