### ISSUE TITLE
Request a DPI Intrinsic Module

### ISSUE THREAD

**Issue by sequencer** [chipsalliance/chisel#3678]
**Type of issue**: Feature Request

**Describe the solution you'd like**

Provide an well-defined intmodule for DPI import and export

**Additional context**

**What is the use case for implementing this feature?**

Relate to
- https://github.com/chipsalliance/t1/blob/master/elaborator/src/DPIModule.scala
- https://github.com/llvm/circt/pull/4856

**Comment by jackkoenig** [comment]
This is finally done!
