### ISSUE TITLE
Chisel website home description

### ISSUE THREAD

**Issue by wptaylor** [chipsalliance/chisel#3710]
**Type of issue**: Bug Report

**Please provide the steps to reproduce the problem:** Link the website on a platform such as Discord which takes the embed description from the Home page.

**What is the current behavior?** Description shows as "Description will go into a meta tag in".

**What is the expected behavior?** I assume the description should be blank or informative.

**Please tell us about your environment:**
- version: `Website as of 03-Jan-2024`
- platform: `Discord (Stable 256231 | Host 1.0.9028 x86 | Windows 10 64-Bit)`

**Other Information**
Image of behavior:
![image](https://github.com/chipsalliance/chisel/assets/93415447/6709496d-9ac2-49eb-a837-62265de54522)

I believe the line causing this is in line 34 of chisel/website/src/pages/index.js
(https://github.com/chipsalliance/chisel/blob/a1d180dee92633f02ac1bb6f0a93a1020f6c044a/website/src/pages/index.js#L34C16-L34C16)

**What is the use case for changing the behavior?**
A clearer description when shared on social platforms.

**Comment by jackkoenig** [comment]
This is now fixed. Thank you for the bug report!

<img width="277" alt="Screenshot 2024-01-27 at 1 04 31 PM" src="https://github.com/chipsalliance/chisel/assets/8584418/d004b144-8801-42bd-817e-aedf72174568">
