### ISSUE TITLE
How to create a BundleLiteral where Bundle contains Option[Data] field

### ISSUE THREAD

**Issue by SihaoLiu** [chipsalliance/chisel#3812]
**Type of issue**: Feature Request

**Is your feature request related to a problem? Please describe.**

Let say I have something like:
```
class OptionalBundle(switch: Boolean) extends Bundle {
  val concrete: UInt         = Input(UInt(8.W))
  val optional: Option[UInt] = if(switch) Some(Input(UInt(8.W))) else None
}
```
How should I create a Bundle Literal by using the `.Lit` function provided by 
```
import chisel3.experimental.BundleLiterals.AddBundleLiteralConstructor
```

**Describe the solution you'd like**
Something I have in mind is:

```
new OptionalBundle.Lit(
    _.concrete -> 11.U, // this is just regular way to build literals
    _.optional.map(_ -> 22.U) // This way looks good to me, but obviously the current Lit function does not support it
)
```

**Comment by sequencer** [comment]
- when you Lit some Bundle, you must make it concrete. in your case, for example: 
```
new OptionalBundle(true).Lit(???)
```
- `Lit` is magic and only consume variable size of `(Data, Data)`, key is the field name, and value is Lit, thus 
```
new OptionalBundle(true).Lit(
  _.concrete -> 11.U,
  _.optional.get -> 9.U
)
new OptionalBundle(false).Lit(
  _.concrete -> 11.U
)
```
should work.

Basically this is a chisel design wut that we doesn't provide a canonical chisel type for Bundle. In your case, there are actually two chisel types can be generated: w or w/o `switch: Boolean`, and they have two different Bundle literal. This is confusing, but cannot be avoid: chisel is a hardware constructing language, and you are actually constructing two different types.
