### ISSUE TITLE
Missing layer definitions when using Definition and Instance

### ISSUE THREAD

**Issue by fzi-antonpaule** [chipsalliance/chisel#4299]
Chisel [Layers](https://www.chisel-lang.org/docs/explanations/layers) do not work as expected when used in conjunction with the [hierarchy mechanism](https://www.chisel-lang.org/docs/cookbooks/hierarchy).
Modules marked with the `@instantiable` annotation can have layer blocks, which is a really neat feature.
Unfortunately, when you try to instantiate such a module using `Definition` and `Instance`, the neccessary layer definitions are not automatically generated in the elaborated FIRRTL circuit.

**Type of issue**: Bug Report

**Please provide the steps to reproduce the problem:**

[Code Snippet @ Scastie](https://scastie.scala-lang.org/fzi-antonpaule/TDPadjr0SxCf7rVN7cWwLw/4)

**What is the current behavior?**

```scala
import chisel3._
import chisel3.experimental.hierarchy.core.{Definition, Instance}
import chisel3.experimental.hierarchy.instantiable
import chisel3.layer.{Convention, Layer, block}

object LayerA extends Layer(Convention.Bind)

class Top extends Module {
  val dSub: Definition[Sub] = Definition(new Sub)
  val subM1: Instance[Sub]  = Instance(dSub)
}

@instantiable
class Sub extends Module {
  block(LayerA) {
    // == Logic
    val a = RegInit(0.U)
  }
}

println(circt.stage.ChiselStage.emitCHIRRTL(new Top))
```

Results in the following FIRRTL circuit, where `layer LayerA, bind:` is missing at the top level:

```firrtl
FIRRTL version 4.0.0
circuit Top :
  module Sub :
    input clock : Clock
    input reset : Reset

    layerblock LayerA : @[src/main/scala/main.scala 17:17]
      regreset REG : UInt, clock, reset, UInt<1>(0h0) @[src/main/scala/main.scala 19:20]


  public module Top :
    input clock : Clock
    input reset : UInt<1>

    inst Sub of Sub @[src/main/scala/main.scala 12:39]
    connect Sub.clock, clock @[src/main/scala/main.scala 12:39]
    connect Sub.reset, reset @[src/main/scala/main.scala 12:39]
```

**What is the expected behavior?**

The expected behavior should be the following generated FIRRTL where `layer LayerA, bind:` is not missing at the top level:

```firrtl
FIRRTL version 4.0.0
circuit Top :
  layer LayerA, bind: << THIS SHOULD BE GENERATED AUTOMATICALLY
  module Sub :
    input clock : Clock
    input reset : Reset

    layerblock LayerA : @[src/main/scala/main.scala 17:17]
      regreset REG : UInt, clock, reset, UInt<1>(0h0) @[src/main/scala/main.scala 19:20]


  public module Top :
    input clock : Clock
    input reset : UInt<1>

    inst Sub of Sub @[src/main/scala/main.scala 12:39]
    connect Sub.clock, clock @[src/main/scala/main.scala 12:39]
    connect Sub.reset, reset @[src/main/scala/main.scala 12:39]
```

**Please tell us about your environment:**
The problem/bug is not related to the environment and is still present in the `7.0.0-M2` release.

**Other Information**
The reason why no layer definitions are created is burried in the [`chisel3.internal.DynamicContext`](https://github.com/chipsalliance/chisel/blob/7bf8b59616fa718ae1a9de1c1f24fb0501bd3444/core/src/main/scala/chisel3/internal/Builder.scala#L475) class 
and how the `Definition` constructor in the [`Definition.do_apply`](https://github.com/chipsalliance/chisel/blob/7bf8b59616fa718ae1a9de1c1f24fb0501bd3444/core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala#L109) method is creating a `new DynamicContext`.
The captured builder context from the method `Builder.captureContext()` contains the layers, but they are not
passed on when a new [`dynamicContext`](https://github.com/chipsalliance/chisel/blob/7bf8b59616fa718ae1a9de1c1f24fb0501bd3444/core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala#L114) is created.

**What is the use case for changing the behavior?**
Layers should work seamlessly with the hierarchy mechanism.

**Comment by seldridge** [comment]
Thanks for the issue report and triage. Your analysis was right on the money for the fix.
