### ISSUE TITLE
How to get the current simulated clock time?

### ISSUE THREAD

**Issue by reoLantern** [chipsalliance/chisel#4328]
I hope to use printf to print the simulation cycle or specific nanoseconds, but there seems to be no corresponding function in the chisel api. I don't mean `timestamp`, which would print the system time.

**Comment by sequencer** [comment]
This is out of Chisel's capability, Here are something you may need refer to: 
- [SystemVerilog LRM](https://standards.ieee.org/ieee/1800/7743/) 
- [vpi_user.h](https://github.com/verilator/verilator/blob/master/include/vltstd/vpi_user.h)
- [svdpi.h](https://github.com/verilator/verilator/blob/master/include/vltstd/svdpi.h)

You can acquire anything you wish with chisel DPI, and use `printf` to print the result out. Or wrap it with blackbox encoding a `$system` call.

**Comment by uenoku** [comment]
There has been some work on emitting the current simulation time from Chisel `printf`
CC: @girishpai @seldridge

**Comment by reoLantern** [comment]
thanks
