### ISSUE TITLE
[FIRRTL] LTL intrinsics are out of the verification layer block

### ISSUE THREAD

**Issue by unlsycn** [chipsalliance/chisel#4429]
**Type of issue**: Bug Report

There are two problems here: 
First, properties generates LTL intrinsics that are outside the Verification layer block.
Second, the above behavior will cause a firtool error `verification operation used in a non-verification context`, which only occurs in specific cases that I have not figured out, and I will provide a minial example to reproduce below.

**Please provide the steps to reproduce the problem:**

```scala
AssumeProperty(
  inputNotValid |=> not(inputFire),
  label = Some("GCD_ASSUMPTION_INPUT_NOT_VALID")
)
```
This Scala code generates the following FIRRTL:

```firrtl
node not = intrinsic(circt_ltl_not : UInt<1>, _T)
node delay = intrinsic(circt_ltl_delay<delay = 1, length = 0> : UInt<1>, UInt<1>(0h1))
node concat = intrinsic(circt_ltl_concat : UInt<1>, _T_5, delay)
node implication = intrinsic(circt_ltl_implication : UInt<1>, concat, not)
node x4_has_been_reset = intrinsic(circt_has_been_reset : UInt<1>, clock, reset)
node x4 = eq(x4_has_been_reset, UInt<1>(0h0))
layerblock Verification :
  layerblock Assume :
    node clock_1 = intrinsic(circt_ltl_clock :
    node _T_6 = eq(x4, UInt<1>(0h0))
    intrinsic(circt_verif_assume<label = "GCD_ASSUMPTION_INPUT_NOT_VALID">, clock_1, _T_6)
```

which works fine with firtool, although I think the intrinsics should be inside the layerblock.

However, this Scala code that just adds another property will break the firtool:

```scala
AssumeProperty(
  inputNotValid |=> not(inputFire),
  label = Some("GCD_ASSUMPTION_INPUT_NOT_VALID")
)

AssertProperty(
  inputFire |=> inputNotFire.repeatAtLeast(1) ### outputFire,
  label = Some("GCD_ALWAYS_RESPONSE")
)
```

The diff tool tells me that the difference between the two firrtl is only the extra property but firtool encounters this error:

```
gcd/src/GCDFormal.scala:68:19: error: verification operation used in a non-verification context
    inputNotValid |=> not(inputFire),
                  ^
gcd/src/GCDFormal.scala:68:19: note: see current operation: %10 = "ltl.delay"(%1) {delay = 1 : i64, length = 0 : i64} : (i1) -> !ltl.sequence
gcd/src/GCDFormal.scala:72:17: note: leaking outside verification context here
  AssertProperty(
                ^
```

The full firrtl files are here:

[good.fir](http://fars.ee/Sf-_)
[bad.fir](http://fars.ee/QI5_)

**Comment by sequencer** [comment]
Can you provide a minimal reproducible chisel via scala-cli?

**Comment by unlsycn** [comment]
> Can you provide a minimal reproducible chisel via scala-cli?

Sure, I'll provide it later.

**Comment by seldridge** [comment]
The first thing that I would try is to put the entire thing inside a `layer.block`. There is some magic that is happening to put the things into layer blocks automatically and then to sink code into layer blocks that is only used by the layer block. However, it may be problematic to rely on that as opposed to doing it explicitly?

**Comment by unlsycn** [comment]
> The first thing that I would try is to put the entire thing inside a `layer.block`. There is some magic that is happening to put the things into layer blocks automatically and then to sink code into layer blocks that is only used by the layer block. However, it may be problematic to rely on that as opposed to doing it explicitly.

Thanks, I'll give it a try.
