### ISSUE TITLE
Bundle doesn't implement === (hardware equality)

### ISSUE THREAD

**Issue by ducky64** [chipsalliance/chisel#832]
**Type of issue**: bug report (?)

**Impact**: API addition (no impact on existing code)

**Development Phase**: proposal

**Other information**
 
Not sure if this is desired behavior or if no one has ever needed to compare a Bundle (or felt strongly enough about not being able to and opened an issue). So far, === is only implemented on Bits.

There may be some nuance in implementing this since Bundles can be bidirectional, so exact semantics (should we want to do this) are up for debate.

For reasons that I can't remember right now, this interacts badly (produces unhelpful and confusing error messages) with trying to instantiate hardware assertions while in a ScalaTest environment, because the Scala compiler guesses you meant the ScalaTest assert and derps hard.

**Comment by jackkoenig** [comment]
It looks like `===` isn't even defined on `Bits`, it's defined on `UInt` and `SInt`. I believe the normal pattern is just to do a `myBundle.asUInt === myOtherBundle.asUInt`. We certainly could define `===` on `Data`. It will require a whitebox macro but hopefully there's a resolution to that in future macros.

**Comment by ekiwi** [comment]
I just stumbled over the same issue. It seems like Equality should be defined on any type that is backed by Bits or that could be a Wire.

**Comment by aswaterman** [comment]
If this does go forward, I think equality should be defined fieldwise, so that it does something sensible if the two bundles have a common field with the same type but different widths.

**Comment by mwachs5** [comment]
Similar for optional items
